main: Replacer.o LRUReplacer.o ClockReplacer.o
	g++ -o main Replacer.o LRUReplacer.o ClockReplacer.o

Replacer.o:Replacer.cpp
	g++ -c Replacer.cpp

LRUReplacer.o:LRUReplacer.cpp
	g++ -c LRUReplacer.cpp

ClockReplacer.o:ClockReplacer.cpp
	g++ -c ClockReplacer.cpp